version: "3.9"

services:

  appclient-service:
    container_name: appclient-service
    build:
      context: ./appclient-service
      dockerfile: Dockerfile.local
    restart: unless-stopped
    env_file:
      - ./appclient-service/.env.example
    ports:
      - "8080:8080"
    depends_on:
      - redis-cache
    networks:
      - app_example_network
    profiles:
      - local

  employee-address-service:
    image: wiremock/wiremock:3.2.0-alpine
    container_name: employee-address-service
    volumes:
      - ./employee-address-service/requests.json:/home/wiremock/mappings/requests.json
    ports:
      - "8081:8080"
    networks:
      - app_example_network

  employee-phone-service:
    image: wiremock/wiremock:3.2.0-alpine
    container_name: employee-phone-service
    volumes:
      - ./employee-phone-service/requests.json:/home/wiremock/mappings/requests.json
    ports:
      - "8082:8080"
    networks:
      - app_example_network

  employee-name-service:
    image: wiremock/wiremock:3.2.0-alpine
    container_name: employee-name-service
    volumes:
      - ./employee-name-service/requests.json:/home/wiremock/mappings/requests.json
    ports:
      - "8083:8080"
    networks:
      - app_example_network

  redis-cache:
    image: redis:7-alpine
    container_name: redis-cache
    restart: always
    environment:
      REDIS_ARGS: "--requirepass password"
    ports:
      - "6379:6379"
    networks:
      - app_example_network

  prometheus:
    image: prom/prometheus:v2.52.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app_example_network
#    extra_hosts:
#      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:10.4.4
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    networks:
      - app_example_network

networks:
  app_example_network: