version: "3.9"

services:

  employee-address-service:
    image: wiremock/wiremock:3.2.0-alpine
    container_name: employee-address-service
    volumes:
      - ./employee-address-service/requests.json:/home/wiremock/mappings/requests.json
    ports:
      - "8081:8080"

  employee-phone-service:
    image: wiremock/wiremock:3.2.0-alpine
    container_name: employee-phone-service
    volumes:
      - ./employee-phone-service/requests.json:/home/wiremock/mappings/requests.json
    ports:
      - "8082:8080"

  employee-name-service:
    image: wiremock/wiremock:3.2.0-alpine
    container_name: employee-name-service
    volumes:
      - ./employee-name-service/requests.json:/home/wiremock/mappings/requests.json
    ports:
      - "8083:8080"

  redis-cache:
    image: redis:7-alpine
    container_name: redis-cache
    restart: always
#    command: redis-server --requirepass password
    ports:
      - "6379:6379"