version: "3.9"

services:

  employee-service:
    image: wiremock/wiremock:3.2.0-alpine
    container_name: employee-service
    volumes:
      - ./.docker/wiremock:/home/wiremock
    ports:
      - "8081:8080"

  redis-cache:
    image: redis:7-alpine
    container_name: redis-cache
    restart: always
#    command: redis-server --requirepass password
    ports:
      - "6379:6379"